//------------------------------------------------------------------------------
// <auto-generated>
//     Ce code a été généré à partir d'un modèle.
//
//     Des modifications manuelles apportées à ce fichier peuvent conduire à un comportement inattendu de votre application.
//     Les modifications manuelles apportées à ce fichier sont remplacées si le code est régénéré.
// </auto-generated>
//------------------------------------------------------------------------------

namespace tp01_cSharp
{
    using System;
    using System.Collections.Generic;
    
    public partial class Admission
    {
        public int ID_admission { get; set; }
        public Nullable<bool> Chirurchie_programmee { get; set; }
        public System.DateTime date_admission { get; set; }
        public Nullable<System.DateTime> date_chirurgie { get; set; }
        public Nullable<System.DateTime> date_congee { get; set; }
        public Nullable<bool> televiseur { get; set; }
        public Nullable<bool> telephone { get; set; }
        public string NAS { get; set; }
        public string Numero_lit { get; set; }
        public string IDMedecin { get; set; }
    
        public virtual Lit Lit { get; set; }
        public virtual Medecin Medecin { get; set; }
        public virtual Patient Patient { get; set; }
    }
}
